### ISSUE TITLE
Error launching steam-idle with game ID

### ISSUE THREAD

**Issue by TheRealIndru** [michael-n0813/linux-idle-master#13]
Hi,

I am getting the below error, starting today:

> [ 10/12/2022 09:44:14 PM ] WELCOME TO IDLE MASTER
> [ 10/12/2022 09:44:14 PM ] Finding games that have card drops remaining
> [ 10/12/2022 09:44:15 PM ] 11 badge pages found.  Gathering additional data
> [ 10/12/2022 09:44:28 PM ] No games have been blacklisted
> [ 10/12/2022 09:44:28 PM ] Idle Master needs to idle 6 games
> [ 10/12/2022 09:44:29 PM ] Starting game App 1252330 to idle cards
> [ 10/12/2022 09:44:29 PM ] Error launching steam-idle with game ID 1252330
> Press Enter to continue...

(and then it exits)

Seems that ID belongs to Deathloop, not sure if it is relevant. Tried blacklisting it, and the next App doesn't work either, so I assume something changed on Steam side?

settings.txt looks OK.

**Comment by michael-n0813** [comment]
OK, I tested just now and it's all working for me.

It seems steam did increase the steamLoginSecure length, it's huge now. Maybe it has to do with the new app?
I tried manually idling deathloop and that works too `python ./steam-ilde.py 1252330` so that is good.

Questions:
1. Are you using the latest release of the git? I updated a few issues.
2. Are you launching the program via `python ./start.py`
3. What is the output of `python --version` . It should say Python 3.xx.xx, if not it would be an alias problem.

**Comment by TheRealIndru** [comment]
Hi,

1. Yes, using latest release.
2. Launching via `python3 ./start.py`
3. Output of `python3 --version` is `Python 3.8.10`

Tried logging out and in (thus refreshing the cookies), restarting PC, no luck.

Output of `python3 ./steam-idle.py 1252330` looks strange:

python3 ./steam-idle.py 1252330
Traceback (most recent call last):
  File "./steam-idle.py", line 7, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

Is this something due to my python3 installation? Worked until now, and all dependencies mentioned in the readme are installed, but I never before tried the ./steam-idle.py script.

**Comment by michael-n0813** [comment]
OK the issue is python3 uses the alias python and you seem to be missing imageTK package

For Ubuntu you need these packages: `sudo apt-get install python3-pil python3-pil.imagetk python3-requests python3-colorama python3-bs4`

To solve the alias problem for python3: `sudo apt-get install python-is-python3`

Then you should be be able to launch the program via `python ./start.py` and all is well again I hope.

**Comment by TheRealIndru** [comment]
Hi,
Confirmed it works now, after I added the imagetk package and I solved the alias problem the way you mentioned.
Thank you very much!! I will close the issue. :)
